### ISSUE TITLE
[PE-D][Tester E] Clear and Help Command is not documented in the User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T10-4/tp#146]
The application loads with sample data initially. Running `clear` removes all the sample data. However, this command is not listed in the user guide. 

Before:

![image.png](https://raw.githubusercontent.com/nreHieW/ped/main/files/959deefd-6c8c-4476-afde-4bb7bcf71067.png)

After:

![image.png](https://raw.githubusercontent.com/nreHieW/ped/main/files/c9f1b328-1ffd-4056-9668-35f1f05ebb6d.png)

Similarly, the `help` command is not documented.

![image.png](https://raw.githubusercontent.com/nreHieW/ped/main/files/9afa43af-34e7-4241-b397-d00a950ee4f8.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: nreHieW/ped#1

**Comment by rngzhi** [comment]
#151

**Comment by Nauxe** [comment]
Similar issue: https://github.com/AY2324S1-CS2103T-T10-4/tp/issues/178

We will add documentation for the clear command.

**Comment by Nauxe** [comment]
Added in: https://github.com/AY2324S1-CS2103T-T10-4/tp/pull/219
