### ISSUE TITLE
[PE-D][Tester E] Viewing person UI is not updating

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T10-4/tp#157]
After viewing a person, running other commands does not update the view person UI section and it still indicate that I am viewing that particular person. 

The same applies to viewing companies 

Screenshot:

![image.png](https://raw.githubusercontent.com/nreHieW/ped/main/files/0a85f129-bc6f-4f00-8c46-77a816de2fd3.png)

Commands ran in order:
view p 1
add p n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friend t/colleague

As a user, I don't know how to navigate back out of the UI page.

After deleting a company because the UI is not updated, I can still view that deleted company 

![image.png](https://raw.githubusercontent.com/nreHieW/ped/main/files/6a123d3c-9b00-48a9-8f39-db01c87e2b8c.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: nreHieW/ped#7

**Comment by Nauxe** [comment]
> As a user, I don't know how to navigate back out of the UI page.

This is not planned.

**Comment by oeggy03** [comment]
Closed. This is not planned.
