### ISSUE TITLE
[PE-D][Tester E] Error message is not consistent for invalid indices

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T10-4/tp#179]
The error messages are not consistent for different invalid indices. For example, there is no one at person index 0 or 1000 therefore the error messages should be the same. 

After running `delete p 0` 
![image.png](https://raw.githubusercontent.com/nreHieW/ped/main/files/a889688e-d845-457e-ab07-ea940f7c191e.png)

After running `delete p 1000`

![image.png](https://raw.githubusercontent.com/nreHieW/ped/main/files/b55caba1-79cf-4d98-9ece-54d59e105af7.png)

After running `delete p -999`

![image.png](https://raw.githubusercontent.com/nreHieW/ped/main/files/ebc14de2-fe01-4a8d-b751-960e511d84aa.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: nreHieW/ped#13

**Comment by rngzhi** [comment]
#182 
#177 
#172 
Same issue
