### ISSUE TITLE
[PE-D][Tester A] Person address field may be unnecessary

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T10-4/tp#183]
For the `add p` command, the user may be confused at how knowing your recruiter's address is helpful in the context of applying for internships, so you might want to elaborate on why these fields are present in the UG, or omit it from Person.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: J-hta-n/ped#3

**Comment by Nauxe** [comment]
Check if we can change address to description
