### ISSUE TITLE
[PE-D][Tester C] No feedback from UI for invalid input for find command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T10-4/tp#187]
### No feedback from UI for invalid input for find command

I entered the invalid command `find c google llc` which is invalid as it contains spaces. However, I did not get any error messages despite pressing "enter" on my keyboard multiple times, and the command finally worked after removing the space in the company name. I suggest to check for a bug caused while parsing the input, and if no bugs are present, an appropriate error message to remind the user should be returned.

<i><video controls><source src="https://raw.githubusercontent.com/kohkaijie/ped/main/files/e8849cda-f0a0-4aab-aa05-6fa3979b6055.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/kohkaijie/ped/main/files/e8849cda-f0a0-4aab-aa05-6fa3979b6055.mp4</i>

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: kohkaijie/ped#8

**Comment by rngzhi** [comment]
#190 
#164 
Same issue
