### ISSUE TITLE
Fix the weird spacing in the user guide

### ISSUE THREAD

**Issue by oeggy03** [AY2324S1-CS2103T-T10-4/tp#217]
![image](https://github.com/AY2324S1-CS2103T-T10-4/tp/assets/80142959/ed19aa7e-422e-4a1c-869e-e9b22726325f)

**Comment by Nauxe** [comment]
I don't think we can do anything about this, since the spacing is something built directly into markdown. A similar thing happens with the header for our Quick Start section

```
## Header1
### Header2
```

shows as:

## Header1
### Header2
