### ISSUE TITLE
[UG/DG] Invalid error message for add p

### ISSUE THREAD

**Issue by Kailash201** [AY2324S1-CS2103T-T10-4/tp#231]
The input: add p n/John  Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney 

I added double space instead of one space for the name

Output: Names should only contain alphabetic characters and spaces, and it should not be blank

**Comment by Tim-Siu** [comment]
Should mention this in DG/UG

**Comment by oeggy03** [comment]
Will throw inside Planned Enhancement

**Comment by Tim-Siu** [comment]
UG is already updated
