### ISSUE TITLE
[Storage]Manual edit of Json crashes (High priority)

### ISSUE THREAD

**Issue by Kailash201** [AY2324S1-CS2103T-T10-4/tp#233]
According to the forum https://github.com/nus-cs2103-AY2324S1/forum/issues/318, the app should show an empty addressbook when the data in the json file has been manually edited, instead of crashing.

![Screenshot 2023-11-11 at 9 49 31 PM](https://github.com/AY2324S1-CS2103T-T10-4/tp/assets/109354852/00240e7e-0143-4afc-8e2a-ff048c8c586e)

I made the phone number invalid.

Your app state
![Screenshot 2023-11-11 at 9 50 29 PM](https://github.com/AY2324S1-CS2103T-T10-4/tp/assets/109354852/f94627f0-a164-47fb-ba34-38d9df1a7d7a)

I think according the forum above, you need to restart your data

**Comment by oeggy03** [comment]
I cannot replicate this error, our app seems to be able to start fresh and accepts commands properly. The addressbook.json updates once an add command is run on the newly empty addressbook:

![image](https://github.com/AY2324S1-CS2103T-T10-4/tp/assets/80142959/87d3669a-75d3-4c67-ac99-2d97f32aacf0)

**Comment by Kailash201** [comment]
Hi, sry, I thought needed to restart the app with sample data. That's all
