### ISSUE TITLE
As a CS student, I can get a list of internship applications with the dates I have interviews during

### ISSUE THREAD

**Issue by Nauxe** [AY2324S1-CS2103T-T10-4/tp#46]
... so I can prepare for each company’s interview in time.

**Comment by lunaroddity** [comment]
Should we edit this issue to relate to internships instead?

**Comment by Nauxe** [comment]
> Should we edit this issue to relate to internships instead?

Yup will do!

**Comment by Nauxe** [comment]
I think we don't plan on having a separate internship list anymore
